### PR TITLE
Fix population specification in #1

### PR DESCRIPTION
**Pull request by janfb**
This is WIP and a first try to use a single excitatory population and to define the subpopulations as views (http://neuralensemble.org/docs/PyNN/neurons.html#views) as suggested by @apdavison . 

I tested it but the results were not the same. So I will have to look into the usage of the subpopulations as views. 

Any comments are welcome.

### CODE REVIEW

**Comment by pgleeson** [comment]
Thanks for looking into this @janfb.

**Comment by sanjayankur31** [comment]
@janfb Do you want to keep working on this branch and we can review and merge it when you think it's complete? Please feel free to request a review from me.

(I've done the model in NEST too, but I need to clean up the code and generate the exact graphs from the paper. On my TODO list :))

**Comment by janfb** [comment]
Yes, I will keep working on this branch and let you know about any results

**Comment by janfb** [comment]
I came across one potential problem. I can define the exc. subpopulations as views on the main exc populations. But the `initialize_values` property of the PopulationView class ([https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/common/populations.py#L837](url)) is not implemented. This is why the subpopulations as views are not initialized and do not generate data. Any ideas?

**Comment by apdavison** [comment]
Thanks for pointing this out. There are several other ways to set initial values:

1. in the `Population` constructor
2. using the `PopulationView.initialize()` method.

**Comment by janfb** [comment]
Good to know that one can also set the initial values in the `Population` constructor. But it does not work for the `PopulationView` constructor. And also your suggestion 2. of using `PopulationView.initialize()` does not work in my case. It will call the `initialize()` method of the `BasePopulation` which will try to set the `initial_values` property of the `PopulationView` object, which will raise the `NotImplementedError` . 

I then thought it might be enough to just initialize all cells of the parent population. But the subpopulation does not spike which is why the results are different. 

Thanks for your help.

**Comment by sanjayankur31** [comment]
@janfb - have you tried this with the latest pynn version? Are you still experiencing the issue? (There's also a different issue now - #7)

**Pull request closed without merging**
