### PR TITLE
Fix for #7

### PR DESCRIPTION
**Pull request by apdavison**
(also a few very minor changes so the code works with Python 3)

### CODE REVIEW

**Comment by sanjayankur31** [comment]
@hcantunc - would you have time to run this updated version to confirm the fix by any chance?

**Comment by hcantunc** [comment]
I still get the same error when I run it with neo 0.5.1

**Comment by apdavison** [comment]
@hcantunc Please can you ensure you are running the `issue7` branch from my fork, and then please can you paste the error traceback that you get?

**Comment by hcantunc** [comment]
I double checked and I do run the `issue7` branch from your fork. This is the traceback that I get:
```
Traceback (most recent call last):
  File "vogelsEtAl2011.py", line 531, in <module>
    numOfSampledNeuronsPattern1_corr, sampledPopPattern1Spikes_corr, numOfSampledNeuronsControl_corr, sampledPopControlSpikes_corr)
  File "../auxRoutines.py", line 761, in plotFig4Column
    plotISICVDoubleHist(ax3, pattern1Spikes, 'red', controlSpikes, 'black')
  File "../auxRoutines.py", line 201, in plotISICVDoubleHist
    neuronISICV = calculateISICV2(neuronSpikes)
  File "../auxRoutines.py", line 91, in calculateISICV2
    neuronISIs = getNeuronISIs2(neuronSpikes)
  File "../auxRoutines.py", line 63, in getNeuronISIs2
    return np.diff(neuronSpikes)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1926, in diff
    return a[slice1]-a[slice2]
  File "/usr/local/lib/python2.7/dist-packages/neo/core/spiketrain.py", line 461, in __sub__
    _check_time_in_range(spikes - time, self.t_start, self.t_stop)
  File "/usr/local/lib/python2.7/dist-packages/neo/core/spiketrain.py", line 66, in _check_time_in_range
    (value, t_start))
ValueError: The first spike ([    5.2            5.2            5.2            5.2            5.2
     5.2            5.2            5.2            5.2            5.2
     5.2            5.2            5.2            5.2            5.2
     5.2            5.2            5.2            5.2            5.2
     5.2            5.2            5.2            5.3            5.3
     5.3            5.3            5.3            5.3            5.3
     5.3            5.3            5.3            5.3            5.3
     5.4            5.4            5.4            5.3            5.4
     5.4            5.4            5.4            5.4            5.4
     5.4            5.4            5.5            5.8            6.6
    37.1           64.8            5.4           66.9            6.7
    70.3           65.4           66.1           66.6           67.1
    67.4           67.7           68.            68.2           68.5
    68.7           69.            69.1           69.3           69.5
    69.6           69.9           70.            70.1           70.3
    70.4           70.5           70.7           70.8           71.            71.
    71.1           71.3           71.3           71.9           71.4
   141.2         1255.7            9.3            7.           162.3
   155.1          169.4            6.8          879.2          282.3
     7.5            7.           298.9          454.6            6.6
     8.5           11.4            8.5          284.1          422.6
   295.5          245.           186.4           13.2           25.2
    94.2            8.3            8.8          364.19999999   227.3
   861.59999999     8.4       ] ms) is before t_start (600.0 ms)
```

**Comment by hcantunc** [comment]
I was getting the following traceback:
```
Traceback (most recent call last):
  File "vogelsEtAl2011.py", line 531, in <module>
    numOfSampledNeuronsPattern1_corr, sampledPopPattern1Spikes_corr, numOfSampledNeuronsControl_corr, sampledPopControlSpikes_corr)
  File "../auxRoutines.py", line 761, in plotFig4Column
    plotISICVDoubleHist(ax3, pattern1Spikes, 'red', controlSpikes, 'black')
  File "../auxRoutines.py", line 201, in plotISICVDoubleHist
    neuronISICV = calculateISICV2(neuronSpikes)
  File "../auxRoutines.py", line 91, in calculateISICV2
    neuronISIs = getNeuronISIs2(neuronSpikes)
  File "../auxRoutines.py", line 63, in getNeuronISIs2
    return np.diff(neuronSpikes)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1926, in diff
    return a[slice1]-a[slice2]
  File "/usr/local/lib/python2.7/dist-packages/neo/core/spiketrain.py", line 461, in __sub__
    _check_time_in_range(spikes - time, self.t_start, self.t_stop)
  File "/usr/local/lib/python2.7/dist-packages/neo/core/spiketrain.py", line 66, in _check_time_in_range
    (value, t_start))
ValueError: The first spike ([    5.2            5.2            5.2            5.2            5.2
     5.2            5.2            5.2            5.2            5.2
     5.2            5.2            5.2            5.2            5.2
     5.2            5.2            5.2            5.2            5.2
     5.2            5.2            5.2            5.3            5.3
     5.3            5.3            5.3            5.3            5.3
     5.3            5.3            5.3            5.3            5.3
     5.4            5.4            5.4            5.3            5.4
     5.4            5.4            5.4            5.4            5.4
     5.4            5.4            5.5            5.8            6.6
    37.1           64.8            5.4           66.9            6.7
    70.3           65.4           66.1           66.6           67.1
    67.4           67.7           68.            68.2           68.5
    68.7           69.            69.1           69.3           69.5
    69.6           69.9           70.            70.1           70.3
    70.4           70.5           70.7           70.8           71.            71.
    71.1           71.3           71.3           71.9           71.4
   141.2         1255.7            9.3            7.           162.3
   155.1          169.4            6.8          879.2          282.3
     7.5            7.           298.9          454.6            6.6
     8.5           11.4            8.5          284.1          422.6
   295.5          245.           186.4           13.2           25.2
    94.2            8.3            8.8          364.19999999   227.3
   861.59999999     8.4       ] ms) is before t_start (600.0 ms)
```

Modifying also the `getNeuronISIs2` function solved the problem.

```
def getNeuronISIs2 (neuronSpikes):
	"Gets the interspike intervals of a neurons within a population"
	if neuronSpikes.size == 0 or neuronSpikes.size == 1:
		return -1 * np.ones(1)
	else:
		return np.diff(neuronSpikes.view(pq.Quantity))
```

**Comment by apdavison** [comment]
Thanks, I didn't spot that there were two versions of the function. I've pushed the second change. Should now be ok.

**Pull request merged**
